# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QLabel

from main import RUN, selenium

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1059, 496)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_1 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_1.setGeometry(QtCore.QRect(50, 60, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit_1.setFont(font)
        self.plainTextEdit_1.setObjectName("plainTextEdit_1")
        self.labelTitre_1 = QtWidgets.QLabel(self.centralwidget)
        self.labelTitre_1.setGeometry(QtCore.QRect(50, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitre_1.setFont(font)
        self.labelTitre_1.setObjectName("labelTitre_1")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(50, 120, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(250, 60, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 120, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.labelTitre_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelTitre_2.setGeometry(QtCore.QRect(250, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitre_2.setFont(font)
        self.labelTitre_2.setObjectName("labelTitre_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(450, 60, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit_3.setFont(font)
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 120, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.labelTitre_3 = QtWidgets.QLabel(self.centralwidget)
        self.labelTitre_3.setGeometry(QtCore.QRect(450, 30, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitre_3.setFont(font)
        self.labelTitre_3.setObjectName("labelTitre_3")
        self.labelTitre_4 = QtWidgets.QLabel(self.centralwidget)
        self.labelTitre_4.setGeometry(QtCore.QRect(50, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitre_4.setFont(font)
        self.labelTitre_4.setObjectName("labelTitre_4")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(50, 210, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit_4.setFont(font)
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 270, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(250, 210, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.plainTextEdit_5.setFont(font)
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 270, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setText("")
        self.label_5.setWordWrap(False)
        self.label_5.setObjectName("label_5")
        self.labelTitre_5 = QtWidgets.QLabel(self.centralwidget)
        self.labelTitre_5.setGeometry(QtCore.QRect(250, 180, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelTitre_5.setFont(font)
        self.labelTitre_5.setObjectName("labelTitre_5")
        self.ButtonSEND = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonSEND.setGeometry(QtCore.QRect(500, 200, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ButtonSEND.setFont(font)
        self.ButtonSEND.setObjectName("ButtonSEND")
        self.ButtonSEND.clicked.connect(self.clicked1)

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 350, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.clickedResult)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(350, 350, 661, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1059, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.list_1 = QtWidgets.QLabel(self.centralwidget)
        self.list_1.setGeometry(QtCore.QRect(920, 30, 81, 371))
        self.list_1.setText("")
        self.list_1.setPixmap(QtGui.QPixmap("list/list_genre.PNG"))
        self.list_1.setObjectName("list_1")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitre_1.setText(_translate("MainWindow", "year"))
        self.labelTitre_2.setText(_translate("MainWindow", "avg_vote"))
        self.labelTitre_3.setText(_translate("MainWindow", "duration"))
        self.labelTitre_4.setText(_translate("MainWindow", "genre"))
        self.labelTitre_5.setText(_translate("MainWindow", "country"))
        self.ButtonSEND.setText(_translate("MainWindow", "SEND"))
        self.pushButton.setText(_translate("MainWindow", "RESULT"))
        self.label.setText(_translate("MainWindow", "..."))

    def clicked1(self):
        text1 = self.plainTextEdit_1.toPlainText()
        self.label_1.setText(text1)
        text2 = self.plainTextEdit_2.toPlainText()
        self.label_2.setText(text2)
        text3 = self.plainTextEdit_3.toPlainText()
        self.label_3.setText(text3)
        text4 = self.plainTextEdit_4.toPlainText()
        self.label_4.setText(text4)
        text5 = self.plainTextEdit_5.toPlainText()
        self.label_5.setText(text5)
        self.update1()


    def clickedResult(self):
        text1 = self.plainTextEdit_1.toPlainText()
        text2 = self.plainTextEdit_2.toPlainText()
        text3 = self.plainTextEdit_3.toPlainText()
        text4 = self.plainTextEdit_4.toPlainText()
        text5 = self.plainTextEdit_5.toPlainText()

        print(text1 + " / " + text2 + " / " + text3 + " / " + text4 + " / " + text5)

        text = RUN(text1, text2, text3, text4, text5)

        self.label.setText(text)
        self.update2()
        selenium(text)

    def update1(self):
        self.label_1.adjustSize()
        self.label_2.adjustSize()
        self.label_3.adjustSize()
        self.label_4.adjustSize()
        self.label_5.adjustSize()

    def update2(self):
        self.label.adjustSize()

    def getText1(self):
        data1 = self.label_1.getText()
        return data1

    def getText2(self):
        data2 = self.label_2.getText()
        return data2

    def getText3(self):
        data3 = self.label_3.getText()
        return data3

    def getText4(self):
        data4 = self.label_4.getText()
        return data4

    def getText5(self):
        data5 = self.label_5.getText()
        return data5

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
